//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalles_Recepcion
    {
        public double Total { get; set; }
        public bool Activo { get; set; }
        public int ID_Producto { get; set; }
        public int ID_RecepcionEncabezado { get; set; }
    
        public virtual Encabezado_Recepcion Encabezado_Recepcion { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
