//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encabezado_Recepcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Encabezado_Recepcion()
        {
            this.Detalles_Recepcion = new HashSet<Detalles_Recepcion>();
        }
    
        public int ID_EncabezadoRecepcion { get; set; }
        public string DescripcionEncabezadoRecepcion { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public bool Activo { get; set; }
        public int ID_Usuario { get; set; }
        public int ID_Bodega { get; set; }
        public int ID_Proveedor { get; set; }
        public System.DateTime fechaVencimiento { get; set; }
        public int ID_TipoProducto { get; set; }
        public int ID_Parametro { get; set; }
    
        public virtual Bodega Bodega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalles_Recepcion> Detalles_Recepcion { get; set; }
        public virtual Parametro Parametro { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Tipo_Producto Tipo_Producto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
