//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Detalles_Recepcion = new HashSet<Detalles_Recepcion>();
        }
    
        public int ID_Producto { get; set; }
        public string DescripcionProducto { get; set; }
        public System.DateTime Fecha_Alta { get; set; }
        public int DiferenciaMesesVencimiento { get; set; }
        public decimal Cubicaje { get; set; }
        public int Empaque { get; set; }
        public decimal CostoBruto { get; set; }
        public decimal Descuento { get; set; }
        public decimal IVA { get; set; }
        public decimal CostoNeto { get; set; }
        public Nullable<int> ID_Ubicacion { get; set; }
        public int ID_TipoProducto { get; set; }
        public Nullable<int> ID_Proveedor { get; set; }
        public int ID_UnidadMedida { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalles_Recepcion> Detalles_Recepcion { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Tipo_Producto Tipo_Producto { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
        public virtual Unidad_Medida Unidad_Medida { get; set; }
    }
}
