//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProveedorTipoProducto
    {
        public int idProveedorTipoProducto { get; set; }
        public int idProveedor { get; set; }
        public int idTipoProducto { get; set; }
        public bool Activo { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
        public virtual Tipo_Producto Tipo_Producto { get; set; }
    }
}
