//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATOS
{
    using ET;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RGSL_ProyectoEntities : DbContext
    {
        public RGSL_ProyectoEntities()
            : base("name=RGSL_ProyectoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bodega> Bodega { get; set; }
        public virtual DbSet<Encabezado_Recepcion> Encabezado_Recepcion { get; set; }
        public virtual DbSet<Modulos> Modulos { get; set; }
        public virtual DbSet<Opcion> Opcion { get; set; }
        public virtual DbSet<Parametro> Parametro { get; set; }
        public virtual DbSet<Permisos> Permisos { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<ProveedorTipoProducto> ProveedorTipoProducto { get; set; }
        public virtual DbSet<Rack> Rack { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<RolTipoProducto> RolTipoProducto { get; set; }
        public virtual DbSet<Tipo_Producto> Tipo_Producto { get; set; }
        public virtual DbSet<Ubicacion> Ubicacion { get; set; }
        public virtual DbSet<Unidad_Medida> Unidad_Medida { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Detalles_Recepcion> Detalles_Recepcion { get; set; }
    }
}
